name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/test.yml'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18.0
      - name: Get project dependencies
        run: go mod download -x
      - name: Run test
        run: go test -v ./...